### ISSUE TITLE
EventLog filling up

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#41]
_Original author: shortdud...@gmail.com (August 16, 2012 16:17:19)_

I have installed v1.6.1 beta on several servers.  I noticed that the eventlogs are filling up with event id 1.  It appears that these logs are just recording a connection from a munin server, however they show up as error messages since event id 1 is not a vaild number.  Is there a way to suppress these logs or change the number so it doesn't create an error?

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=36_

**Comment by Strykar** [comment]
Any scope of a fix for this?

<code>The description for Event ID 1 from source munin-node cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Name: uptime

the message resource is present but the message is not found in the string/message table</code>

Most of the other events it logs have data that looks destined for the munin-master:

<code>The description for Event ID 1 from source munin-node cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Config:
graph_title Uptime
graph_category system
graph_args --base 1000 -l 0
graph_info System Up Time is the elapsed time (in seconds) that the computer has been running since it was last started.  This counter displays the difference between the start time and the current time.
graph_vlabel System Up Time
uptime.label 0
uptime.draw AREA
uptime.type GAUGE
.


the message resource is present but the message is not found in the string/message table
</code>

This happens, incessantly, for for other plugins like Processor, Disktime amongst others but they all appear to work just fine.

**Comment by pchamo** [comment]
I have Munin Node version 1.7.3.2 installed and the bug is still present:

The description for Event ID 1 from source munin-node cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PerfCounter plugin: processor: counter path \\SRV-XXXX\Processor(_Total)\% Processor Time, Processor

The message resource is present but the message was not found in the message table
