### ISSUE TITLE
Binaries to download

### ISSUE THREAD

**Issue by mrPsycho** [munin-monitoring/munin-node-win32#47]
Hello,

will you ever upload binaries? 
or where i can find latest one?

**Comment by jakubczaplicki** [comment]
+1 I've spent too much time looking for an executable, and ended up downloading an old version from Sourceforge. It would be good to clean up the project on SF and Google Code code pages to point to a single page. URL of the old executables : http://en.sourceforge.jp/projects/sfnet_munin-nodewin32/ https://code.google.com/p/munin-node-win32/downloads/list

**Comment by rrzefox** [comment]
+1 for cleaning up SF and google code - the last one should be done VERY soon, because code.google.com will go read-only in 4 days! It's also certainly a good idea to remove the SF one, before they start doing what they did to GIMP (replace the installer with a crapware-riddled version).
The reason the download-link here on github is so hard to find is because github removed the /download/ feature in 2013. The direct link still works, but it could be removed at any time by github, and it isn't linked to anywhere.
Regarding new binaries, I have tried to make some, but things are complicated by the fact that the latest version of the code on google code and here differ. The binaries include at least the PerfCounterCustomPlugin that isn't included in the sourcecode here on github, but in the latest revision on google code. There might very well be further differences. Nonetheless, I have tried to make a new binary, built from the source tree available at https://github.com/rrzefox/munin-node-win32/tree/recompile - it includes  the PerfCounterCustomPlugin and my two open pull requests on top of the "master" from here. If you want to give it a try, it is available at https://grid.rrze.fau.de/~unrz191/munin-node-win32-1.6.1.1-installer.exe - no warranties of any kind.

**Comment by steveschnepp** [comment]
Sorry for the decaying status of munin-node-win32. I'm not able to compile it anymore, due to lack of ready-to-use box and lack of time to recreate one.

I have the plan to take munin-c to replace this eventually. It will be a 64 bit clean, portable implementation. As munin-c should also replace the Perl node in the medium term it should be quite beneficial.

**Comment by combrs** [comment]
I'm (and tons ot other people) interested in binaries with fixed (disabled/able to configure) issue, when every connect to service logged. on github there is many forks, and in one of them this is fixed: https://github.com/joshrobb/munin-node-win32   -" turn of verbose event log logging (controled via [MuninNode] DebugLog=true/false) " . In all binaries what I tried it is NOT fixed. Can you merge with that fix? (commit https://github.com/joshrobb/munin-node-win32/commit/f4605659115b39d2f471f4483b051202ff635ac5 )

**Comment by TcT2k** [comment]
I've made binaries available [here](https://github.com/TcT2k/munin-node-win32/releases) from my PR #67

**Comment by NotoriousPyro** [comment]
VS2015 build from fork https://github.com/dellin/munin-node-win32/tree/dellin_head

 https://pyronexus.com:8001/job/dellin-munin-node-win32/

**Comment by lemontree23** [comment]
For those of you guys looking at this in 2020, I took it upon myself to fix up some non-working code and also add a lot o new S.M.A.R.T plugins.
I also built a binary installer for you so you do not have to do anything.
https://github.com/lemontree23/munin-node-win32/releases/tag/1.7.3.0

**Comment by lemontree23** [comment]
Newest binaries in 'Releases' Tab
